ALTER TABLE "Restaurant" ALTER COLUMN "approvalStatus" SET DEFAULT 'PENDING';
ALTER TABLE "Restaurant" ALTER COLUMN "karmaScore" SET DEFAULT 0;

ALTER TABLE "NGO" ALTER COLUMN "approvalStatus" SET DEFAULT 'PENDING';
ALTER TABLE "NGO" ALTER COLUMN "karmaScore" SET DEFAULT 0;
ALTER TABLE "NGO" ALTER COLUMN "isVerified" SET DEFAULT false;
